import org.gradle.plugin.use.PluginDependenciesSpec
import org.gradle.plugin.use.PluginDependencySpec

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
    const val io_gitlab_arturbosch_detekt: String = "1.7.1" // available: "1.9.1"

    const val com_squareup_retrofit2: String = "2.8.1"

    const val org_jetbrains_kotlin: String = "1.3.72"

    const val androidx_lifecycle: String = "2.2.0"

    const val com_squareup_moshi: String = "1.8.0" // available: "1.9.2"

    const val androidx_room: String = "2.2.5"

    const val io_arrow_kt: String = "0.10.5"

    const val org_koin: String = "2.1.5"

    const val com_android_tools_build_gradle: String = "3.6.3"

    const val androidx_test_ext_junit: String = "1.1.1"

    const val junit_junit: String = "4.13"

    const val de_fayard_buildsrcversions_gradle_plugin: String = "0.7.0"

    const val navigation_safe_args_gradle_plugin: String = "2.2.2"

    const val navigation_fragment_ktx: String = "2.2.2"

    const val navigation_runtime_ktx: String = "2.2.2"

    const val logging_interceptor: String = "4.7.0"

    const val navigation_fragment: String = "2.3.0-alpha04"

    const val legacy_support_v4: String = "1.0.0"

    const val navigation_ui_ktx: String = "2.2.2"

    const val constraintlayout: String = "1.1.3"

    const val collection_ktx: String = "1.1.0"

    const val espresso_core: String = "3.2.0"

    const val activity_ktx: String = "1.1.0"

    const val fragment_ktx: String = "1.2.4"

    const val recyclerview: String = "1.1.0"

    const val lint_gradle: String = "26.6.3"

    const val viewbinding: String = "3.6.3"

    const val appcompat: String = "1.1.0"

    const val core_ktx: String = "1.2.0"

    const val timber: String = "4.7.1"

    const val aapt2: String = "3.6.3-6040484"

    const val mockk: String = "1.10.0"

    const val coil: String = "0.11.0"

    const val gson: String = "2.8.6"

    /**
     * Current version: "5.6.4"
     * See issue 19: How to update Gradle itself?
     * https://github.com/jmfayard/buildSrcVersions/issues/19
     */
    const val gradleLatestVersion: String = "6.4.1"
}

/**
 * See issue #47: how to update buildSrcVersions itself
 * https://github.com/jmfayard/buildSrcVersions/issues/47
 */
val PluginDependenciesSpec.buildSrcVersions: PluginDependencySpec
    inline get() =
        id("de.fayard.buildSrcVersions").version(Versions.de_fayard_buildsrcversions_gradle_plugin)
